secrets:
  ttl: 15m
  private-key: &privateKey |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn
    NhAAAAAwEAAQAAAQEAsnj8HHcWNtAEqo3YcHg2zXJqhqlHkUwsZFIC7OJl3lmdN8buT1rr
    reUA8cJSfbh/R4oYZWT0CXHuOevyMMI7rqYym7l9qwTXEaXF0gpSGZcGFmvPmqXgZbhXIm
    CNyM/ho8YoG8ZQZtSVpKIscWMsUNpW9swFBJy02GvVzVBFI5wkfSoJWFgpz9a/cbwF4gYv
    LYHPteLepPLfuhBc9G69WfBRN7x6XWAQ7s8VDrZr4nhWIXCKxoZcCwkHkfplZIxmrikhit
    5tuNWMGy++jIEP47D8V2lsm2jNnn6EVndge7Y33JqbamXJzpqMgkJ1ng+qkTkZi7V8O552
    1/wFj104XQAAA9CxTxudsU8bnQAAAAdzc2gtcnNhAAABAQCyePwcdxY20ASqjdhweDbNcm
    qGqUeRTCxkUgLs4mXeWZ03xu5PWuut5QDxwlJ9uH9HihhlZPQJce456/IwwjuupjKbuX2r
    BNcRpcXSClIZlwYWa8+apeBluFciYI3Iz+GjxigbxlBm1JWkoixxYyxQ2lb2zAUEnLTYa9
    XNUEUjnCR9KglYWCnP1r9xvAXiBi8tgc+14t6k8t+6EFz0br1Z8FE3vHpdYBDuzxUOtmvi
    eFYhcIrGhlwLCQeR+mVkjGauKSGK3m241YwbL76MgQ/jsPxXaWybaM2efoRWd2B7tjfcmp
    tqZcnOmoyCQnWeD6qRORmLtXw7nnbX/AWPXThdAAAAAwEAAQAAAQA8jnqUuf+Kl6iNqlV/
    S/rkWOc2S+fhsCP74ivl7qe7+1IyI8immmYPef2JCnNs/xYI0x2WAdwf/E1lz948lxsjFn
    djiVvPlHPZJBNsQl47GphRMUGe6puqSBMgsfxJ3+di55CiY/bR/V3NH83Op2TZBkytruog
    938RU/2WjZ74BqjDsJfnC9s0PHZzXgqwesVdq+Xc++v5WLz99MDSwOo/QftSRD/DAPnj5W
    cKVpW24sWQ8vnDvOicV7fuEC6tqbgyWmbRJGBE67F/eomkY0I0sWwTBYr0RXn/HHXo4Wfc
    QTAwc8y8sKWHdVnxc+IZ+y5Kj2d9raliEOpfccjS9FntAAAAgQDbnm6RQBtzujPnz8uve4
    OsqDdXl0dvq26qA8HvvWKtaXHGFjO1svKYLRpOE8S5zs82RfH76kjFTn1ROMzQI+9KwXsP
    getBhTfrFWLe1xxhpcSbuYW1ovdXoXVQtew0jsUBYEwBA7+kbq7CkPFpNMKCJFWQDLaigZ
    ObCGNuMwmvgAAAAIEA4X/Qa57rxswUX0F/iNDwK/Ws3N3KenBc8ZeCk3/BdhD3dpBCXrw4
    3y+EaWZS5zjdYfue8qhBRSnbXtmY1FX65DlR5u/QnKxntl4q3viMzEaaeLhiVD7hopxafW
    vTdJA9LptVNLeu8gn+CDZGDwrYJ7+qRrS+Z11JtvxbksgK/3sAAACBAMqc0J+4WBCKCBYq
    f1oBcmmUrQSEVXzoZnjxXVKP3Et8LSXlYkEHuynopvRH1spsAjbXikFpGpfiUHUulq0Rdw
    V0XKHLy4YWmEmhkr0TiPw54+58NRBxbfD9qy6D3bGIekNK9vE+V9FDKA2kLxsuqi6thxwX
    gGlcV3v9Domt/fQHAAAAFGluYWl0YWxpQE1CUC1kZS1JZGlyAQIDBAUG
    -----END OPENSSH PRIVATE KEY-----

  public-key: &publicKey |
    -----BEGIN RSA PUBLIC KEY-----
    MIIBCgKCAQEAsnj8HHcWNtAEqo3YcHg2zXJqhqlHkUwsZFIC7OJl3lmdN8buT1rr
    reUA8cJSfbh/R4oYZWT0CXHuOevyMMI7rqYym7l9qwTXEaXF0gpSGZcGFmvPmqXg
    ZbhXImCNyM/ho8YoG8ZQZtSVpKIscWMsUNpW9swFBJy02GvVzVBFI5wkfSoJWFgp
    z9a/cbwF4gYvLYHPteLepPLfuhBc9G69WfBRN7x6XWAQ7s8VDrZr4nhWIXCKxoZc
    CwkHkfplZIxmrikhit5tuNWMGy++jIEP47D8V2lsm2jNnn6EVndge7Y33JqbamXJ
    zpqMgkJ1ng+qkTkZi7V8O5521/wFj104XQIDAQAB
    -----END RSA PUBLIC KEY-----
